# Generated by Django 4.1.4 on 2023-03-10 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common_app', '0003_doctors_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=50)),
                ('patient_email', models.CharField(max_length=40)),
                ('patient_phone', models.BigIntegerField()),
                ('patient_gender', models.CharField(max_length=15)),
                ('booking_date', models.DateField()),
                ('booking_time', models.TimeField()),
                ('patient_description', models.CharField(max_length=200)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('doctor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common_app.doctors')),
            ],
            options={
                'db_table': 'booking',
            },
        ),
    ]
