# Generated by Django 4.1.4 on 2023-03-14 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reference_no',
            field=models.CharField(default='', max_length=40),
        ),
    ]
