# Generated by Django 4.1.4 on 2023-03-16 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_booking_reference_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='patient_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
