# Generated by Django 4.1.4 on 2023-03-23 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0005_alter_contact_phone'),
        ('patient', '0003_booking_patient_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common_app.patient'),
        ),
        migrations.AddField(
            model_name='booking',
            name='patient_age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
