# Generated by Django 4.1.4 on 2023-03-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=40)),
                ('admin_email', models.CharField(max_length=40)),
                ('admin_password', models.CharField(default='', max_length=10)),
            ],
            options={
                'db_table': 'admin',
            },
        ),
    ]
