# Generated by Django 4.1.4 on 2023-03-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0002_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
