# Generated by Django 4.1.4 on 2023-03-23 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0003_booking_patient_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.CharField(max_length=300)),
                ('medication_name', models.CharField(max_length=50)),
                ('purpose', models.CharField(max_length=50)),
                ('dosage', models.CharField(max_length=40)),
                ('route', models.CharField(max_length=30)),
                ('frequency', models.CharField(max_length=50)),
                ('status', models.CharField(default='active', max_length=20)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.booking')),
            ],
            options={
                'db_table': 'prescriptions',
            },
        ),
    ]
